---
collections:
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: infra.aap_configuration
  - name: infra.aap_utilities
  - name: infra.ah_configuration
  - name: infra.eda_configuration
  - name: infra.ee_utilities
  - name: infra.osbuild
  - name: infra.aap_configuration
  - name: containers.podman

roles: []
