---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation--25/ansible-dev-tools-rhel8:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: "{{ playbook_dir }}/templates/ansible.cfg.j2"
    dest: configs/ansible.cfg

dependencies:
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_builder: |
    RUN microdnf install -y python3.11 python3.11-pip python3.11-devel python3.11-pyyaml 

  prepend_final: |
    # Install Chrome dependencies
    RUN microdnf install -y liberation-fonts libappindicator-gtk3 liberation-sans-fonts \
                            liberation-serif-fonts xdg-utils libXScrnSaver libX11 \
                            mesa-libGLU redhat-lsb

    # Download and install Chrome
    RUN curl -sSLO https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && \
        microdnf install -y google-chrome-stable_current_x86_64.rpm && \
        rm -f google-chrome-stable_current_x86_64.rpm

    # Standard upgrade steps
    RUN microdnf upgrade -y \
        && python3 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel jmespath six

  append_final: |
    USER root
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /etc/ansible/ansible.cfg
