---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: "../../templates/ansible.cfg"
    dest: configs/ansible.cfg

dependencies:
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml
  ansible_core:
    package_pip: ansible-core>=2.15.0
  ansible_runner:
    package_pip: ansible-runner>=2.3.0

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_builder: |
    RUN microdnf install -y python3.11 python3.11-pip python3.11-devel python3.11-pyyaml 
    
    # Work around missing openshift-clients package in RHEL 8
    RUN mkdir -p /usr/bin && echo '#!/bin/bash' > /usr/bin/oc && chmod +x /usr/bin/oc 
    
    # Create wrapper script for microdnf that ignores openshift-clients
    RUN mv /usr/bin/microdnf /usr/bin/microdnf.real && \
        echo '#!/bin/bash' > /usr/bin/microdnf && \
        echo 'args=()' >> /usr/bin/microdnf && \
        echo 'for arg in "$@"; do' >> /usr/bin/microdnf && \
        echo '  if [[ "$arg" != "openshift-clients" ]]; then' >> /usr/bin/microdnf && \
        echo '    args+=("$arg")' >> /usr/bin/microdnf && \
        echo '  fi' >> /usr/bin/microdnf && \
        echo 'done' >> /usr/bin/microdnf && \
        echo '/usr/bin/microdnf.real "${args[@]}"' >> /usr/bin/microdnf && \
        chmod +x /usr/bin/microdnf 

  prepend_final: |
    RUN microdnf upgrade -y \
        && python3 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel jmespath six

  append_final: |
    USER root
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /etc/ansible/ansible.cfg

